ex1

In [5]:
import numpy as np
@np.vectorize
def far_to_cel(temp):
    return round((temp-32)*5/9, 1)

arr = np.array([12, 33, 43, 64])
print(far_to_cel(arr))

[-11.1   0.6   6.1  17.8]


ex2

In [6]:
@np.vectorize
def calculate_power(num, power):
    return num**power

nums = np.array([2, 3, 4, 5])
powers = np.array([1, 2, 3, 4])

calculated = calculate_power(nums, powers)
print(calculated)

[  2   9  64 625]


ex3

In [8]:
coefs = np.array([
    [4, 5, 6],
    [3, -1, 1],
    [2, 1, -2]
])

eq = np.array([7, 4, 5])

np.linalg.solve(coefs, eq)

array([ 1.7027027 ,  0.62162162, -0.48648649])

In [10]:
coefs = np.array([
    [10, -2, 3],
    [-2, 8, -1],
    [3, -1, 6]
])

eq = np.array([12, -5, 15])

np.linalg.solve(coefs, eq)

array([ 0.48963731, -0.2253886 ,  2.21761658])

#IMAGE

In [16]:
from PIL import Image
with Image.open('birds.jpg') as img:
    img_arr = np.array(img)

reversed_img_arr = img_arr[:, ::-1]
img_rev = Image.fromarray(reversed_img_arr)
img_rev.save('reversed_birds.jpg')
img_upside_down = Image.fromarray(reversed_img_arr[::-1, :])
img_upside_down.save('upd_birds.png')

In [35]:
with Image.open('birds.jpg') as img:
    img_arr = np.array(img)

img_arr[:, :, 0] = np.where(img_arr[:,:,0]<255, img_arr[:,:,0]+10, 255)
img = Image.fromarray(img_arr)
img.save('brightness.jpg')

In [36]:
with Image.open('birds.jpg') as img:
    img_arr = np.array(img)

img_arr[100:200,100:200,:] = [0, 0, 0]
img = Image.fromarray(img_arr)
img.save('mask.jpg')