ex1

In [4]:
import numpy as np
a1 = np.arange(10, 50, 5)
print(a1)

array([10, 15, 20, 25, 30, 35, 40, 45])

ex2

In [9]:
a2 = np.arange(9).reshape(3, 3)
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


ex3

In [11]:
a3 = np.eye(3)
print(a3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


ex4

In [13]:
a4 = np.arange(27).reshape(3, 3, 3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


ex5

In [19]:
a5 = np.random.randint(0, 100, (10, 10))
print(f'max value: {a5.max()}')
print(f'min value: {a5.min()}')

max value: 98
min value: 0


ex6

In [23]:
arr = np.random.randint(0, 10, 30)
print(arr.mean())

4.4


ex7

In [24]:
matrix = np.random.randint(0, 100, (5, 5))

# Min-Max Normalization
normalized_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())

print("Original Matrix:\n", matrix)
print("Normalized Matrix:\n", normalized_matrix)


Original Matrix:
 [[63  8 85 92 39]
 [81 83 86 74 15]
 [56 56 49 29 76]
 [18 49 23 41  3]
 [98 68 22 75 61]]
Normalized Matrix:
 [[0.63157895 0.05263158 0.86315789 0.93684211 0.37894737]
 [0.82105263 0.84210526 0.87368421 0.74736842 0.12631579]
 [0.55789474 0.55789474 0.48421053 0.27368421 0.76842105]
 [0.15789474 0.48421053 0.21052632 0.4        0.        ]
 [1.         0.68421053 0.2        0.75789474 0.61052632]]


ex8

In [31]:
arr1 = np.random.randint(0, 10, (5, 3))
arr2 = np.random.randint(0, 10, (3, 2))
print(arr1)
print(arr2)
print('Multiplied:')
print(arr1@arr2)

[[1 6 3]
 [4 5 0]
 [8 8 5]
 [2 1 7]
 [4 5 0]]
[[1 7]
 [6 3]
 [7 4]]
Multiplied
[[ 58  37]
 [ 34  43]
 [ 91 100]
 [ 57  45]
 [ 34  43]]


ex9

In [32]:
arr1 = np.random.randint(0, 10, (3, 3))
arr2 = np.random.randint(0, 10, (3, 3))
print('arr1:')
print(arr1)
print('arr2:')
print(arr2)
print(np.dot(arr1, arr2))

arr1:
[[1 1 7]
 [1 2 0]
 [9 1 8]]
arr2:
[[4 6 8]
 [9 5 8]
 [1 3 7]]
[[ 20  32  65]
 [ 22  16  24]
 [ 53  83 136]]


ex10

In [34]:
arr1 = np.random.randint(0, 10, (4, 4))
print('Original:')
print(arr1)
print('Transpose:')
print(arr1.transpose())

Original:
[[3 0 2 7]
 [9 0 4 8]
 [3 1 1 0]
 [5 4 3 7]]
Transpose:
[[3 9 3 5]
 [0 0 1 4]
 [2 4 1 3]
 [7 8 0 7]]


ex11

In [37]:
# Create a 3x3 matrix
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

# Compute the determinant
det_A = np.linalg.det(A)

print("Matrix A:\n", A)
print("Determinant of A:", det_A)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of A: 0.0


ex12

In [38]:
# Create a 3x4 matrix (A) with random integers
A = np.random.randint(1, 10, (3, 4))

# Create a 4x3 matrix (B) with random integers
B = np.random.randint(1, 10, (4, 3))

# Compute the matrix product (A × B)
C = np.dot(A, B) 

print("Matrix A (3x4):\n", A)
print("Matrix B (4x3):\n", B)
print("Matrix Product C (3x3):\n", C)


Matrix A (3x4):
 [[5 5 6 2]
 [1 2 8 5]
 [9 5 8 6]]
Matrix B (4x3):
 [[9 5 3]
 [8 3 2]
 [8 5 8]
 [8 1 7]]
Matrix Product C (3x3):
 [[149  72  87]
 [129  56 106]
 [233 106 143]]


ex13

In [39]:
# Create a random 3x3 matrix
A = np.random.randint(1, 10, (3, 3))

# Create a random 3-element column vector
v = np.random.randint(1, 10, (3, 1))

# Compute the matrix-vector product
result = np.dot(A, v)  

print("Matrix A (3x3):\n", A)
print("Column Vector v (3x1):\n", v)
print("Matrix-Vector Product (3x1):\n", result)


Matrix A (3x3):
 [[6 1 1]
 [1 2 9]
 [1 1 9]]
Column Vector v (3x1):
 [[8]
 [9]
 [2]]
Matrix-Vector Product (3x1):
 [[59]
 [44]
 [35]]


In [ ]:
# Create a 3x3 matrix (A)
A = np.array([[2, 3, 1], 
              [4, 5, 6], 
              [7, 8, 9]])

# Create a 3x1 column vector (b)
b = np.array([[1], 
              [2], 
              [3]])

# Solve for x using np.linalg.solve()
x = np.linalg.solve(A, b)

print("Matrix A:\n", A)
print("Vector b:\n", b)
print("Solution x:\n", x)


In [41]:
# Create a 5x5 matrix with random integers
A = np.random.randint(1, 10, (5, 5))

# Compute row-wise sums (sum along axis=1)
row_sums = np.sum(A, axis=1)

# Compute column-wise sums (sum along axis=0)
col_sums = np.sum(A, axis=0)

print("Matrix A (5x5):\n", A)
print("Row-wise sums:\n", row_sums)
print("Column-wise sums:\n", col_sums)


Matrix A (5x5):
 [[4 8 6 8 2]
 [8 1 5 6 9]
 [2 8 1 4 2]
 [7 1 2 7 4]
 [5 5 8 3 7]]
Row-wise sums:
 [28 29 17 21 28]
Column-wise sums:
 [26 23 22 28 24]
